import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
    <body>
        {/* Audio global (tidak berhenti saat pindah halaman) */}
        <audio
          autoPlay
          loop
          controls
          id="bg-music"
          className="fixed bottom-4 left-4 z-50 opacity-80"
        >
          <source src="/music/lagu.mp3" type="audio/mpeg" />
          Browser kamu tidak mendukung audio.
        </audio>

        {children}
      </body>
    </html>
  );
}
